package com.termux.terminal.bridge

import android.view.InputDevice
import android.view.KeyEvent
import kotlin.jvm.JvmStatic

/**
 * Filters out key events generated by the fingerprint sensor gesture area.
 *
 * <p>Many devices register the fingerprint sensor as an input device with its own
 * {@code KeyCharacterMap}. A tap on the sensor then arrives as a regular key event
 * whose unicode mapping resolves to {@code ~} (0x7E) in the terminal. Such sensors
 * are reported with {@code SOURCE_TOUCHPAD} and never have an alphabetic keyboard,
 * while real hardware keyboards are either alphabetic or use {@code SOURCE_KEYBOARD},
 * so the predicate below is safe: only a non-alphabetic touchpad with a
 * fingerprint-like key code/scan code is ignored.</p>
 *
 * <p>This is a pure predicate on primitives so it can be unit tested without
 * allocating Android framework objects.</p>
 */
object FingerprintKeyFilter {

    /**
     * Whether the key event should be ignored as a fingerprint sensor activation.
     *
     * @param keyCode The event key code (e.g. {@link KeyEvent#KEYCODE_UNKNOWN}).
     * @param source The event source bitmask (e.g. {@link InputDevice#SOURCE_TOUCHPAD}).
     * @param keyboardType The device keyboard type, or
     * {@link InputDevice#KEYBOARD_TYPE_NON_ALPHABETIC} when unknown.
     * @param scanCode The raw scan code (0 or 4 are the values seen on
     * fingerprint gesture devices).
     * @return {@code true} if the event should be swallowed.
     */
    @JvmStatic
    fun shouldIgnore(keyCode: Int, source: Int, keyboardType: Int, scanCode: Int): Boolean {
        if (keyCode != KeyEvent.KEYCODE_UNKNOWN && scanCode != 4 && scanCode != 0) return false
        val fromTouchpad = (source and InputDevice.SOURCE_TOUCHPAD) != 0
        val alphabetic = keyboardType == InputDevice.KEYBOARD_TYPE_ALPHABETIC
        return fromTouchpad && !alphabetic
    }
}